classdef CodeCleaner < handle
    % CodeCleaner - Cleans generated code of branding and trademarks
    %
    % Ensures generated MATLAB/Simulink code is clean and professional,
    % without any third-party branding or repository-specific names.

    methods
        function obj = CodeCleaner()
            % Constructor
        end

        function cleanCode = clean(obj, code)
            % Main cleaning function - removes all branding from code
            cleanCode = code;

            % Remove common brand patterns
            cleanCode = obj.removeBrandNames(cleanCode);
            cleanCode = obj.removeRepositoryNames(cleanCode);
            cleanCode = obj.removeTrademarks(cleanCode);
            cleanCode = obj.standardizeComments(cleanCode);
            cleanCode = obj.removeWatermarks(cleanCode);
        end

        function code = removeBrandNames(obj, code)
            % Remove brand names and product names
            brandPatterns = {
                'MATLAB AI Agent',
                'AI Agent',
                'Claude',
                'Anthropic',
                'OpenAI',
                'GPT',
                'ChatGPT',
                'Copilot',
                'GitHub Copilot'
            };

            for i = 1:length(brandPatterns)
                pattern = brandPatterns{i};
                % Replace in comments
                code = regexprep(code, ['%.*?' pattern '.*'], '% Power Systems Analysis Tool');
                % Replace in strings
                code = regexprep(code, ["'" pattern "'"], "'Power Systems Tool'");
            end
        end

        function code = removeRepositoryNames(obj, code)
            % Remove repository-specific names
            repoPatterns = {
                'matlab-power-agent',
                'matlab_power_agent',
                'Matlab Agent',
                'power-agent',
                'power_agent'
            };

            for i = 1:length(repoPatterns)
                pattern = repoPatterns{i};
                code = regexprep(code, pattern, 'power-systems-tool', 'IgnoreCase', true);
            end
        end

        function code = removeTrademarks(obj, code)
            % Remove or replace trademarked terms
            trademarkMap = containers.Map();
            trademarkMap('Simulink') = 'SIMULINK';
            trademarkMap('MATLAB') = 'MATLAB';
            trademarkMap('MathWorks') = 'MathWorks';

            % Keep standard product names but remove promotional text
            promoPatterns = {
                'powered by.*',
                'generated by.*',
                'created with.*',
                'using.*AI',
                'AI-powered'
            };

            for i = 1:length(promoPatterns)
                code = regexprep(code, ['%.*?' promoPatterns{i} '.*'], '%', 'IgnoreCase', true);
            end
        end

        function code = standardizeComments(obj, code)
            % Standardize comment format
            lines = strsplit(code, newline);

            for i = 1:length(lines)
                line = lines{i};

                % Remove author attributions
                if contains(line, '@author') || contains(line, 'Author:')
                    lines{i} = '';
                    continue;
                end

                % Remove generation timestamps (keep for reproducibility)
                if contains(line, 'Generated on:')
                    lines{i} = '% Generated MATLAB Code';
                    continue;
                end

                % Standardize header
                if contains(line, 'This file was automatically generated')
                    lines{i} = '% Auto-generated code for power systems analysis';
                end
            end

            code = strjoin(lines, newline);
        end

        function code = removeWatermarks(obj, code)
            % Remove any watermark text
            watermarkPatterns = {
                'DO NOT DELETE',
                'Auto-generated',
                'Generated file',
                'Machine generated'
            };

            for i = 1:length(watermarkPatterns)
                pattern = watermarkPatterns{i};
                code = regexprep(code, ['%.*?' pattern '.*'], '', 'IgnoreCase', true);
            end
        end

        function cleanCode = cleanFunctionNames(obj, code, prefix)
            % Remove or replace custom prefixes from function names
            % This ensures generated code uses standard naming
            patterns = {
                [prefix '_'],
                ['ai_' prefix '_'],
                ['auto_']
            };

            cleanCode = code;
            for i = 1:length(patterns)
                cleanCode = regexprep(cleanCode, ...
                    ['function\s+' patterns{i} '(\w+)'], ...
                    'function $1', ...
                    'IgnoreCase', true);
            end
        end

        function cleanCode = ensureCleanHeader(obj, code, title)
            % Ensure code has a clean, professional header
            if nargin < 3
                title = 'Power Systems Analysis';
            end

            header = sprintf([
                '%% %s\n']
                '%% Auto-generated MATLAB Code\n'
                '%% \n'
                '%% This code was generated for power system analysis purposes.\n'
                '%% Review and validate results before using in production.\n'
                '\n'], title);

            % Remove existing header comments
            lines = strsplit(code, newline);
            dataStart = 1;
            inHeader = true;

            for i = 1:length(lines)
                line = strtrim(lines{i});
                if startsWith(line, '%')
                    if inHeader
                        dataStart = i + 1;
                    end
                else
                    if inHeader && ~isempty(line)
                        inHeader = false;
                        dataStart = i;
                        break;
                    end
                end
            end

            % Get code without old header
            if dataStart > 1
                codeWithoutHeader = strjoin(lines(dataStart:end), newline);
            else
                codeWithoutHeader = code;
            end

            cleanCode = [header newline codeWithoutHeader];
        end

        function isClean = validateClean(obj, code)
            % Validate that code is free of branding
            isClean = true;

            checkPatterns = {
                'Claude', 'Anthropic', 'OpenAI', 'GPT', 'ChatGPT',
                'matlab-power-agent', 'AI Agent'
            };

            for i = 1:length(checkPatterns)
                if contains(code, checkPatterns{i}, 'IgnoreCase', true)
                    isClean = false;
                    return;
                end
            end
        end

        function report = getCleaningReport(obj, originalCode, cleanedCode)
            % Report what was cleaned
            report = struct();
            report.originalLength = length(originalCode);
            report.cleanedLength = length(cleanedCode);
            report.charactersRemoved = report.originalLength - report.cleanedLength;

            % Count changes
            report.changes = {};

            if ~strcmp(originalCode, cleanedCode)
                report.changes{end+1} = 'Code was modified during cleaning';
            end

            if obj.validateClean(cleanedCode)
                report.changes{end+1} = 'Final code passed cleanliness check';
            else
                report.changes{end+1} = 'Warning: Some branding may remain';
            end
        end
    end
end
